my_app/my_app/urls.py
from django import views
from django.contrib import admin
from django.urls import path,include
from teacher.views import index, login, logout,register
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('teacher.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_app/teacher/urls.py
from . import views
from django.urls import path
from teacher.views import index, login, logout,register, sendmail,teacher

app_name = 'teacher'
urlpatterns = [
    path('', index, name='index'),
    path('login', login, name='login'),
    path('register', register, name="register"),
    path('logout/', logout, name='logout'),
    path('teacher/', teacher, name='teacher'),
    path('sendmail/', sendmail, name='sendmail'),
]

my_app/teacher/models.py
from distutils.command.upload import upload
import email
from email.mime import image
from statistics import mode
from turtle import title
from django.forms import CharField
from django.db import models
from django.contrib.auth.models import User


class BecomeLecturers(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to="img/%y")
    content=models.CharField(max_length=200)
class TutorBlock(models.Model):
    image=models.ImageField(upload_to="img/%y", blank=True, null=True) 
    title=models.CharField(max_length=200, blank=True, null=True) 
    content=models.CharField(max_length=200, blank=True, null=True)
class TutorBlock2(models.Model):
    title=models.CharField(max_length=200) 
    content=models.CharField(max_length=200) 
class TutorIcon(models.Model):
    image=models.ImageField(upload_to="img/%y") 
    title=models.CharField(max_length=200) 
    content=models.CharField(max_length=200)
class TutorIcon2(models.Model):
    image=models.ImageField(upload_to="img/%y") 
class WhyMakeTeacher(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to="img/%y")
    content=models.CharField(max_length=200)
class WhyMakeTeacher2(models.Model):
    image=models.ImageField(upload_to="img/%y")
    title=models.CharField(max_length=200)
    content=models.CharField(max_length=200)
class ActivitiesCultural(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to="img/%y")
    content=models.CharField(max_length=200)
class ActivitiesCultural2(models.Model):
    image=models.ImageField(upload_to="img/%y")
class AboutUs(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to="img/%y")
    content=models.CharField(max_length=200)
class AboutUs2(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to="img/%y")
    name=models.CharField(max_length=200)
    position=models.CharField(max_length=200)
class RegisterTeacher(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to="img/%y")
    content=models.CharField(max_length=200)
class Partners(models.Model):
    title=models.CharField(max_length=200)
    content=models.CharField(max_length=200)
class Partners2(models.Model):
    image=models.ImageField(upload_to="img/%y")

class Teacher(models.Model):
    name=models.CharField(max_length=200)
    number_phone= models.IntegerField()
    email=models.CharField(max_length=200)
    cv=models.FileField(upload_to ='cv/%y')

my_app/teacher/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ('username','password')

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField( widget=forms.EmailInput(attrs= {'class' : 'form-control c-placeholder-login'}))

    class Meta:
        model = get_user_model()
        fields = ('username','email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']       
        if commit:
            user.save()
            
        return user

my_app/teacher/views.py
from email import message
import email
import json
from multiprocessing import AuthenticationError, context
from re import template
from telnetlib import LOGOUT
from unittest import loader
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from re import template
from django.shortcuts import redirect, render
from django.template import loader
from django.views import View
from django.contrib.auth import authenticate
from teacher.forms import LoginForm
from .models import AboutUs, AboutUs2, ActivitiesCultural, ActivitiesCultural2, BecomeLecturers, Partners, Partners2, RegisterTeacher, Teacher, TutorBlock, TutorBlock2, TutorIcon, TutorIcon2, WhyMakeTeacher, WhyMakeTeacher2
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .forms import UserCreationForm, UserRegistrationForm
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.core.mail import send_mail
from email.message import EmailMessage

@login_required
def index(request):
    


    myBecomeLecturers=BecomeLecturers.objects.all().values()
    myTutorBlock=TutorBlock.objects.all().values()
    myTutorBlock2=TutorBlock2.objects.all().values()
    myTutorIcon=TutorIcon.objects.all().values()
    myTutorIcon2=TutorIcon2.objects.all().values()
    myWhyMakeTeacher=WhyMakeTeacher.objects.all().values()
    myWhyMakeTeacher2=WhyMakeTeacher2.objects.all().values()
    myActivitiesCultural=ActivitiesCultural.objects.all().values()
    myActivitiesCultural2=ActivitiesCultural2.objects.all().values()
    myAboutUs=AboutUs.objects.all().values()
    myAboutUs2=AboutUs2.objects.all().values()
    myRegisterTeacher=RegisterTeacher.objects.all().values()
    myPartners=Partners.objects.all().values()
    myPartners2=Partners2.objects.all().values()
    template = loader.get_template('index.html')
    context= {
        'myBecomeLecturers':myBecomeLecturers,
        'myTutorBlock':myTutorBlock,
        'myTutorBlock2':myTutorBlock2,
        'myTutorIcon':myTutorIcon,
        'myTutorIcon2':myTutorIcon2,
        'myWhyMakeTeacher':myWhyMakeTeacher,
        'myWhyMakeTeacher2':myWhyMakeTeacher2,
        'myActivitiesCultural':myActivitiesCultural,
        'myActivitiesCultural2':myActivitiesCultural2,
        'myAboutUs2':myAboutUs2,
        'myAboutUs':myAboutUs,
        'myRegisterTeacher':myRegisterTeacher,
        'myPartners':myPartners,
        'myPartners2':myPartners2,
    }
    return HttpResponse(template.render(context, request))
    
def sendmail(request):
    if request.method == 'POST':
        sender_email = request.POST['email']

        mail = EmailMessage(
            'This is title',
            'Cảm ơn bạn đã liên hệ với chúng tôi. Chúng tôi sẽ thông báo tới bạn khi có thông tin mới nhất về Teky!!!',
            settings.EMAIL_HOST_USER,
            [sender_email]
        )
        mail.fail_silently = True
        mail.send()
        messages.success(request, "Đăng ký thành công")
    return render(request, 'index.html', {})


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    if request.method=="POST":
        user_name = request.POST['username']
        matkhau = request.POST['password']
        my_user = authenticate(username=user_name, password=matkhau)
        if my_user is not None:
            auth_login(request, my_user)
            return HttpResponseRedirect('/') 
        else:
            messages.success(request, ("Incorrect account or password"))
            return redirect('login')
    return render(request, 'login.html', context={'form':LoginForm()})    

    




def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)    
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('/')
        else:           
            for error in list(form.errors.values()):
                messages.error(request, error)

    form = UserRegistrationForm()
    return render(
        request=request,
        template_name="register.html",
        context={"form": form}
    )
    


def logout(request):    
    auth.logout(request)
    return HttpResponseRedirect('/')


def teacher(request):
    if request.method=="POST":
        name=request.POST['name']
        number_phone=request.POST['number_phone']
        email=request.POST['email']
        cv=request.POST['cv']
        teacher= Teacher(name=name,number_phone=number_phone,email=email,cv=cv)
        teacher.save()
        messages.success(request, "Đăng ký thành công")
        return redirect('/')

my_app/teacher/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, shrink-to-fit=no">
        <meta http-equiv="content-language" content="vi">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="author" content="Template">
        <meta name="COPYRIGHT" content="© Template">
        <meta name="robots" content="noodp,index,follow">
        <meta name="google" content="notranslate">
        <meta name="keywords" content="">
        <meta name="description" content="">
        <link rel="shortcut icon" href="images/favicon.ico">
        <title>Teky LMS - Login</title>
        <!--Include CSS-->
        <link href="{% static 'css/style2.css' %}" rel="stylesheet">

    </head>
    <body>
        <div id="DIV_2">
            <!--Content page part-->
        
            <div id="DIV_3">
                <div id="DIV_4">
                    <div id="DIV_5">
                        <div id="DIV_6">
                            <div id="DIV_7">
                                <div id="DIV_8">
                                    <img src="http://static-html.teky.edu.vn/tekylms20html/static/images/teky/logo-login.png" id="IMG_9" alt='' />
                                </div>
                                <div id="DIV_10">
                                    <form method="POST" action="{% url 'teacher:login' %}">
                                        {% csrf_token%}
                                        
                                    <div id="DIV_11">
                                        <input id="INPUT_12" {{form.username}} 
                                        
                                        
                                        <div id="DIV_13" placeholder="Số điện thoại; Email hoặc Tên đăng nhập">
                                            
                                        </div>
                                    </div>
                                    <div id="DIV_17">
                                        <input id="INPUT_18" type="password" {{form.password}}                                    
                                        <div id="DIV_19" placeholder="Mật khẩu">
                                        </div> 
                                        <button id="BUTTON_21">
                                            <i id="I_22"></i>
                                        </button>
                                        {% if messages %}
                                            {% for message in messages %}
                                            <div class="message">
                                             {{message}}
                                            </div>
                                            {% endfor %}
                                        {% endif %}
                                    </div> 
                                        <button id="BUTTON_24">
                                            <span id="SPAN_25" type="submit">Đăng nhập</span>
                                            <div id="DIV_26">
                                                bằng mật khẩu
                                            </div><i id="I_27"></i>
                                        </button>
                                    </form>
                                    
                                    <div id="DIV_28">
                                        <span id="SPAN_29">Bạn không nhớ</span> <a href="#" id="A_30"> <b id="B_31">mật khẩu?</b></a>
                                    </div>
                                    <div id="DIV_32">
                                        <span id="SPAN_33">Hoặc</span>
                                    </div> 
                                    <button id="BUTTON_34">
                                        <i id="I_35"></i><span id="SPAN_36">Đăng nhập bằng Facebook</span>
                                    </button> 
                                    <button id="BUTTON_37">
                                        <i id="I_38"></i><span id="SPAN_39">Đăng nhập bằng Gmail</span>
                                    </button>
                                </div>
                                <div id="DIV_40">
                                    <div id="DIV_41">
                                        Bạn chưa có tài khoản? <a href="register" id="A_42"><span id="SPAN_43">Đăng ký ngay</span></a>
                                    </div>
                                    <div id="DIV_44">
                                        <span id="SPAN_45">Made with</span><i id="I_46"></i><span id="SPAN_47">by TEKY</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="DIV_48">
                            <img src="http://static-html.teky.edu.vn/tekylms20html/static/images/teky/login.png" id="IMG_49" alt='' /> <span id="SPAN_50"> <b id="B_51">Welcome!</b></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Optional JavaScript part-->
        
        <!--jQuery first, then Popper.js, then Bootstrap JS-->
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        <!--Page specific javascripts part-->
    </body>
</html>

my_app/teacher/templates/register.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, shrink-to-fit=no">
        <meta http-equiv="content-language" content="vi">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="author" content="Template">
        <meta name="COPYRIGHT" content="© Template">
        <meta name="robots" content="noodp,index,follow">
        <meta name="google" content="notranslate">
        <meta name="keywords" content="">
        <meta name="description" content="">
        <link rel="shortcut icon" href="images/favicon.ico">
        <title>Teky LMS - Register</title>
        <!--Include CSS-->
        <link href="{% static 'css/style3.css' %}" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    </head>
    <body>
        
        <div id="DIV_1">
            <!--Content page part-->
            
            
            
            <div id="DIV_2">
                <div id="DIV_3">
                    <div id="DIV_4">
                        <div id="DIV_5">
                            <div id="DIV_6">
                                <div id="DIV_7">
                                    <img src="http://static-html.teky.edu.vn/tekylms20html/static/images/teky/logo-login.png" id="IMG_8" alt='' />
                                </div>
                                
                                <form method="POST" action="{% url 'teacher:register' %}">                            
                                    {% if messages %}
                                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                        {% for message in messages %}
                                        
                                            <div class="error">
                                                {{message}}
                                                
                                            </div>   
                                        
                                        {% endfor %}
                                        </div>
                                    {% endif %}
                                    <div id="DIV_9">  
                                        
                                        {% csrf_token%}
                                        <div id="DIV_10">                                       
                                            <input required type="text" id="INPUT_11"  placeholder="Username" {{form.username}}
                                        </div>
                                        <div id="DIV_10">
                                            <input required type="email" id="INPUT_11"  placeholder="Email" {{form.email}}
                                        </div>
                                        <div id="DIV_10">
                                            <input required type="password" id="INPUT_11"  placeholder="Password" {{form.password1}}
                                        </div>
                                        <div id="DIV_10">
                                            <input required type="password" id="INPUT_11"  placeholder="Confirm Password" {{form.password2}}
                                        </div>
                                         
                                        <button id="BUTTON_21" tyle="submit">
                                            <span id="SPAN_22" >Đăng ký<div id="DIV_23">
                                                miễn phí
                                            </div></span>
                                            <i id="I_24"></i>
                                        </button>
                                        
                                        
                                    </form>   
    
                                </div>
                                <div id="DIV_33">
                                    <span id="SPAN_34">Bạn đã có tài khoản?</span> <a href="login" id="A_35">Đăng nhập</a> <span id="SPAN_36">ngay</span>
                                </div>
                                <div id="DIV_37">
                                    <div id="DIV_38">
                                        <span id="SPAN_39">Made with</span><i id="I_40"></i><span id="SPAN_41">by TEKY</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="DIV_42">
                            <img src="http://static-html.teky.edu.vn/tekylms20html/static/images/teky/register.png" id="IMG_43" alt='' /><span id="SPAN_44">Xin chào!<b id="B_45">Đăng ký tài khoản!</b></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="" async defer></script>
        
    </body>
</html>